In [2]:
import numpy as n
import matplotlib.pyplot as m

In [2]:
inputs = [1.2, 5.1, 2.1]
weights = [3.1, 2.1, 8.7]
bias = 3

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
output

35.7

In [3]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
output

2.3

In [4]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] +inputs[3]*weights[3]+ bias
output

4.8

In [5]:
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] +inputs[3]*weights1[3]+ bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] +inputs[3]*weights2[3]+ bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] +inputs[3]*weights3[3]+ bias3]
output

[4.8, 1.21, 2.385]

In [6]:
inputs = [1, 2, 3, 2.5]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

layer_outputs = []
for neuron_weights, neuron_biases in zip(weights, biases):
  neuron_output = 0
  for n_input, weight in zip(inputs, neuron_weights):
    neuron_output += n_input*weight
  neuron_output += neuron_biases
  layer_outputs.append(neuron_output)

layer_outputs

[4.8, 1.21, 2.385]

In [7]:
inputs = [1, 2, 3, 2.5]

weights=[0.2, 0.8, -0.5, 1.0]
bias = 2

output = n.dot(inputs, weights) + bias

output

4.8

In [8]:
inputs = [1, 2, 3, 2.5]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

output = n.dot(weights, inputs) + biases

output

array([4.8  , 1.21 , 2.385])

In [9]:
inputs = [1, 2, 3, 2.5]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

output = n.dot(inputs, weights) + biases

output

ValueError: shapes (4,) and (3,4) not aligned: 4 (dim 0) != 3 (dim 0)

In [ ]:
inputs = [[1, 2, 3, 2.5],
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

output = n.dot(weights, inputs) + biases

output

In [11]:
inputs = [[1, 2, 3, 2.5],          #transposing the matrix of weights to get the dot product
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]


biases = [2,3,0.5]

output = n.dot(inputs, n.array(weights).T) + biases

output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [10]:
inputs = [[1, 2, 3, 2.5],          #transposing the matrix of weights to get the dot product
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]


biases = [2,3,0.5]
weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_output = n.dot(inputs, n.array(weights).T) + biases

layer2_output = n.dot(layer1_output, n.array(weights2).T) + biases2

layer2_output

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [9]:
X        = [[1, 2, 3, 2.5],         # Here X, is set of inputs having
            [2.0, 5.0, -1.0, 2.0],  # 3 different sets (samples) of 4 input values.
            [-1.5, 2.7, 3.3, -0.8]] #
n.random.seed(0)

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10* n.random.randn(n_inputs, n_neurons)
    self.biases = n.zeros((1, n_neurons))    #Shape: (1×5), meaning one bias per output neuron.
  def forward(self, inputs ):
    self.output = n.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5) #4 → Number of input neurons (matches the number of features in each sample).
                          #5 → Number of output neurons (the layer transforms the input into 5 outputs per sample).
                          #Shape: (4×5) → Because each of the 4 input neurons is connected to each of the 5 output neurons.
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print("Layer 1 \n",layer1.output) #(3×5) output means:
                     #You got 5 output values per sample (from 5 output neurons).
                     #Since you had 3 different input samples, you got 3 sets of 5 outputs.
layer2.forward(layer1.output)
print("Layer 2 \n",layer2.output)

Layer 1 
 [[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
Layer 2 
 [[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
