In [2]:
import numpy as n
import matplotlib.pyplot as m

In [2]:
inputs = [1.2, 5.1, 2.1]
weights = [3.1, 2.1, 8.7]
bias = 3

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
output

35.7

In [3]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
output

2.3

In [4]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] +inputs[3]*weights[3]+ bias
output

4.8

In [5]:
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] +inputs[3]*weights1[3]+ bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] +inputs[3]*weights2[3]+ bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] +inputs[3]*weights3[3]+ bias3]
output

[4.8, 1.21, 2.385]

In [6]:
inputs = [1, 2, 3, 2.5]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

layer_outputs = []
for neuron_weights, neuron_biases in zip(weights, biases):
  neuron_output = 0
  for n_input, weight in zip(inputs, neuron_weights):
    neuron_output += n_input*weight
  neuron_output += neuron_biases
  layer_outputs.append(neuron_output)

layer_outputs

[4.8, 1.21, 2.385]

In [7]:
inputs = [1, 2, 3, 2.5]

weights=[0.2, 0.8, -0.5, 1.0]
bias = 2

output = n.dot(inputs, weights) + bias

output

4.8

In [8]:
inputs = [1, 2, 3, 2.5]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

output = n.dot(weights, inputs) + biases

output

array([4.8  , 1.21 , 2.385])

In [9]:
inputs = [1, 2, 3, 2.5]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

output = n.dot(inputs, weights) + biases

output

ValueError: shapes (4,) and (3,4) not aligned: 4 (dim 0) != 3 (dim 0)

In [ ]:
inputs = [[1, 2, 3, 2.5],
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2,3,0.5]

output = n.dot(weights, inputs) + biases

output

In [11]:
inputs = [[1, 2, 3, 2.5],          #transposing the matrix of weights to get the dot product
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]


biases = [2,3,0.5]

output = n.dot(inputs, n.array(weights).T) + biases

output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [10]:
inputs = [[1, 2, 3, 2.5],          #transposing the matrix of weights to get the dot product
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]


biases = [2,3,0.5]
weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_output = n.dot(inputs, n.array(weights).T) + biases

layer2_output = n.dot(layer1_output, n.array(weights2).T) + biases2

layer2_output

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [15]:
X        = [[1, 2, 3, 2.5],         # Here X, is set of inputs having
            [2.0, 5.0, -1.0, 2.0],  # 3 different sets (samples) of 4 input values.
            [-1.5, 2.7, 3.3, -0.8]] #
n.random.seed(0)

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10* n.random.randn(n_inputs, n_neurons)
    self.biases = n.zeros((1, n_neurons))    #Shape: (1×5), meaning one bias per output neuron.
  def forward(self, inputs ):
    self.output = n.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,50) #4 → Number of input neurons (matches the number of features in each sample).
                          #5 → Number of output neurons (the layer transforms the input into 5 outputs per sample).
                          #Shape: (4×5) → Because each of the 4 input neurons is connected to each of the 5 output neurons.
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print("Layer 1 \n",layer1.output) #(3×5) output means:
                     #You got 5 output values per sample (from 5 output neurons).
                     #Since you had 3 different input samples, you got 3 sets of 5 outputs.
layer2.forward(layer1.output)
print("Layer 2 \n",layer2.output)

Layer 1 
 [[ 5.45196730e-01  1.41404182e-01 -5.71621434e-01  7.21722609e-02
  -1.95430799e-01  4.05155370e-01  2.65885573e-01 -4.48860662e-01
   1.52829141e-01  3.03211043e-01  3.15671843e-01  8.27713129e-01
  -1.07537988e-01  2.61818277e-01 -3.06888339e-01  4.04838908e-01
  -1.42510009e-01 -3.60655177e-01  3.31078356e-01  2.80877160e-01
   2.33661496e-01 -1.58979882e-01  6.18002862e-01 -8.60222954e-02
  -1.59487278e-01 -1.56890318e-01 -5.00982060e-01  2.47903356e-01
   1.78772716e-01  2.84777286e-01 -5.37008526e-01  3.60184834e-02
  -3.58850486e-01 -1.05163000e+00  2.28413263e-01  1.97228307e-01
   2.55666392e-01  3.48046609e-02 -3.18971941e-01  2.38495267e-01
  -9.56082191e-01  3.01067448e-01 -8.87906794e-02  2.88891403e-01
   8.66070659e-01  3.37964467e-01 -2.04078562e-01  9.75904059e-01
   1.00293980e-02  2.54780451e-01]
 [-2.96886202e-01  7.50927141e-01 -8.15574365e-02 -4.04364831e-01
   4.57042319e-01 -3.08347417e-01  4.89965377e-01 -2.02763133e-02
  -7.59592750e-01 -3.34866371e-

ValueError: shapes (3,50) and (5,2) not aligned: 50 (dim 1) != 5 (dim 0)

In [11]:
n.random.seed(0)

X        = [[1, 2, 3, 2.5],
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]]

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

for i in inputs: # Relu Activation function
  if i > 0:
    output.append(i)
  else:
    output.append(0)

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [1]:
pip install nnfs

In [3]:
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

X        = [[1, 2, 3, 2.5],
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]]

X, y = spiral_data(100, 3)

class Layer_Dense:

  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10* n.random.randn(n_inputs, n_neurons)
    self.biases = n.zeros((1, n_neurons))

  def forward(self, inputs ):
    self.output = n.dot(inputs, self.weights) + self.biases


class Activation_ReLu:  #Activation function in the play
  def forward(self, inputs):
    self.output = n.maximum(0, inputs)

layer1 = Layer_Dense(2,5)

layer1.forward(X)
activation1 = Activation_ReLu()
activation1.forward(layer1.output)

print("Layer 1 \n",activation1.output)

Layer 1 
 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]]


In [5]:
import math

layer_outputs = [4.8, 1.21, 2.385]
E = math.e

exp_values = []

for output in layer_outputs:
  exp_values.append(E**output) # exponential function

print(exp_values)

[121.51041751873483, 3.353484652549023, 10.859062664920513]


In [7]:
import math

layer_outputs = [4.8, 1.21, 2.385]
E = math.e

exp_values = []

for output in layer_outputs:
  exp_values.append(E**output) # exponential function

print(exp_values)

norm_base = sum(exp_values) # normalization of values for probability distribution
norm_values = []

for value in exp_values:
  norm_values.append(value / norm_base)

print(norm_values)
print(sum(norm_values))



[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [16]:
layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]


exp_values = n.exp(layer_outputs)

print(n.sum(layer_outputs, axis=1))
# norm_values = exp_values/n.sum(exp_values)

# print(exp_values)
# print(norm_values)
# print(sum(norm_values))



[8.395 7.29  2.487]


In [18]:
layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]


exp_values = n.exp(layer_outputs)

print(n.sum(layer_outputs, axis=1, keepdims = True))
# norm_values = exp_values/n.sum(exp_values)

# print(exp_values)
# print(norm_values)
# print(sum(norm_values))



[[8.395]
 [7.29 ]
 [2.487]]


In [21]:
layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]


exp_values = n.exp(layer_outputs)


norm_values = exp_values/n.sum(exp_values, axis=1, keepdims = True)

# print(exp_values)
print(norm_values)
print(sum(norm_values))



[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]
[2.40819096 0.38306452 0.20874452]


In [24]:
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:

  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10* n.random.randn(n_inputs, n_neurons)
    self.biases = n.zeros((1, n_neurons))

  def forward(self, inputs ):
    self.output = n.dot(inputs, self.weights) + self.biases


class Activation_ReLu:  #Activation function in the play
  def forward(self, inputs):
    self.output = n.maximum(0, inputs)

class Activation_softmax:
  def forward(self, inputs):
    exp_values = n.exp(inputs - n.max(inputs, axis=1, keepdims=True))
    probabilities = exp_values / n.sum(exp_values, axis=1, keepdims=True)
    self.output = probabilities

X,y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLu()

dense2 = Layer_Dense(3,3)
activation2 = Activation_softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

# 1. we first created fake weights of size 2,3
# 2. then applied those weights on the dataset X
# 3. then we applies relu activation function on it
# 4. then we applies the fake weights 3x3 on the output of relu activation fuction
# 5. then we applies softmax activation function

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [25]:
# Categorical - Class entropy: Calculating loss

softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0]

loss = -(math.log(softmax_output[0])*target_output[0] +
         math.log(softmax_output[1])*target_output[1] +
         math.log(softmax_output[2])*target_output[2])
print(loss)

0.35667494393873245
